### ISSUE TITLE
Allignment

### ISSUE THREAD

**Issue by anjanaouseph** [vgnshiyer/ASU-sparkysundevil-resume-template#1]
Hey,
When you add multiple education histories the alignment doesn't come out correctly:
\newkeycommand{\educationItem}[university,college,program,graduation,grade,coursework]{
    {\bf \commandkey{program}} \hfill {\commandkey{graduation}} \\
    {\commandkey{university}} \hfill \ifcommandkey{grade}{\commandkey{grade}}{}
}

\education{
    \educationItem[
    university=Arizona State University{,} Tempe{,} AZ,
    graduation=Dec 2024 (Expected),
    program=M.S.{,} Computer Science,
    grade=3.78 GPA,
]
\\
\educationItem[
    university=National Institute of Technology Calicut{,} Kerala{,} India,
    graduation=Jun 2020,
    program=B.Tech.{,} Electronics and Communication Engineering,
    grade= 3.34 GPA,
]

}

Any idea how to fix this?
Thanks in advance!

![image](https://github.com/vgnshiyer/ASU-sparkysundevil-resume-template/assets/40512980/eab9aa35-42b1-4bc9-b080-ddf19301e14e)

**Comment by vgnshiyer** [comment]
Thanks for the issue. Will be looking into it. Feel free to open a pull request if you find a solution for the same. @anjanaouseph

**Comment by anjanaouseph** [comment]
Sure, will do

**Comment by vgnshiyer** [comment]
Can you try adding a new line in the command for the university and the grade? @anjanaouseph 
```
\newkeycommand{\educationItem}[university,college,program,graduation,grade,coursework]{
     {\bf \commandkey{program}} \hfill {\commandkey{graduation}} \\
     {\commandkey{university}} \hfill \ifcommandkey{grade}{\commandkey{grade} \\}{}
}
```
The horizontal fill requires you to break the line for it fill the entire space.

**Comment by anjanaouseph** [comment]
It works but you will have so much extra spaces between two education histories.
![image](https://github.com/vgnshiyer/ASU-sparkysundevil-resume-template/assets/40512980/28d87448-10da-44b9-a26a-1072a74d5251)

I tried removing the newline after grade:
  `\newkeycommand{\educationItem}[university,college,program,graduation,grade,coursework]{
       {\bf \commandkey{program}} \hfill {\commandkey{graduation}} \\
       {\commandkey{university}} \hfill \ifcommandkey{grade}{\commandkey{grade} }{}
  }`

but the allignment issue comes back
![image](https://github.com/vgnshiyer/ASU-sparkysundevil-resume-template/assets/40512980/d1036ac0-d1af-46d2-95a2-17722e92bff1)

**Comment by anjanaouseph** [comment]
Ideally the 3.34 GPA should be below 3.78 GPA and i think there shouldn't be so much extra space.

**Comment by vgnshiyer** [comment]
Hello @anjanaouseph, Thank you for reporting this issue. This issue has been identified as a 'Known Issue' and has a workaround mentioned in the updated Docs.  👉 [here](https://github.com/vgnshiyer/ASU-sparkysundevil-resume-template?tab=readme-ov-file#known-issues)
